### ISSUE TITLE
The module stops working whenever I change character

### ISSUE THREAD

**Issue by priestmain123** [caali-hackerman/battle-notify#1]
As title, It works for the first character I log in. If I want to change caracter I must reboot my game otherwise the module doesn't work nymore. Happens the same even if I just go on character selection and log back the same character I was online on before.

It didn't use to be like this before the proxy update

**Comment by caali-hackerman** [comment]
This issue was fixed by 75ee6b463c4313f4e267709dfd2284785ea9d959.
