### ISSUE TITLE
notifications don't show up after a while

### ISSUE THREAD

**Issue by Cupcakes123** [caali-hackerman/battle-notify#2]
The module works fine for a little bit, but after couple hours the notifications disappear? I'd have to restart proxy and the game for it to work again. I also tried re-installing the module, but it didn't help.

**Comment by Cupcakes123** [comment]
problem still persists.

**Comment by bigworld12** [comment]
related to https://github.com/caali-hackerman/battle-notify/issues/1 i think

**Comment by caali-hackerman** [comment]
Hi and thanks for the report! Please note that I'm merely keeping this mod alive (updating defs etc), and not really actively maintaining it. I'll try to find some spare time to track down the issue at some point, but that won't be anytime soon... sorry for the inconvenience!

**Comment by Cupcakes123** [comment]
Ah okay! Thank you! Take your time ^_^

**Comment by caali-hackerman** [comment]
This issue was fixed by 75ee6b463c4313f4e267709dfd2284785ea9d959.
